myreports_options = {
    'pipeline': {
        'parent': 'Sales',
        'child': 'Pipeline Report (1065)'
    },
    'csat_surveys': {
        'parent': 'Sales',
        'child': 'Customer Satisfaction Surveys (3099)'
    },
    'app_to_close': {
        'parent': 'Sales',
        'child': 'Approval To Closing Report (1953)'
    },
    'branch_pipeline': {
        'parent': 'Sales',
        'child': 'Branch Pipeline Report (3054)'
    },
    'branch_production_details': {
        'parent': 'Sales',
        'child': 'Branch Production Details (3073)'
    },
    'cot_surveys': {
        'parent': 'Sales',
        'child': 'Close on Time Fund on Time Survey Results (1179)'
    },
    'funding_by_referral': {
        'parent': 'Sales',
        'child': 'Funding By Referral Source (2006)'
    },
    'loan_type_activity': {
        'parent': 'sales',
        'child': 'Loan Type Activity (1605)'
    },
    'locked_pipeline': {
        'parent': 'sales',
        'child': 'Lock Report (3053)'
    },
    'yoy_production': {
        'parent': 'sales',
        'child': 'Year over Year Production Activity Report (1848)'
    },
    'turn_time': {
        'parent': 'raw',
        'child': 'https://myreports.supremelending.com/ReportServer/Reserved.ReportViewerWebControl.axd?ExecutionID=h2tabj55wmboeoj2gh0po455&Culture=1033&CultureOverrides=False&UICulture=9&UICultureOverrides=False&ReportStack=1&ControlID=25c80cf70fba479c86a056d1ecabaa6a&OpType=Export&FileName=Turn+Time+Report+By+Title+(1092)&ContentDisposition=OnlyHtmlInline&Format=EXCELOPENXML'
    }
}

funding_by_referral_columns = [
    'Loan Number', 'LOS System', 'Branch', 'Property State',
    'Funded Month', 'Borrower', 'Units', 'Total Loan Amount',
    'Loan Type', 'Loan Program', 'Lien Position', 'Loan Purpose',
    'Loan Officer', 'Lead Source', 'Referral Source',
    'Referral Name', 'Prior Year', 'Year To Date', 'Prior Month',
    'Month To Date'
]

stop_words = {'a',
              'about',
              'above',
              'after',
              'again',
              'against',
              'all',
              'also',
              'am',
              'an',
              'and',
              'any',
              'are',
              "aren't",
              'as',
              'at',
              'be',
              'because',
              'been',
              'before',
              'being',
              'below',
              'between',
              'both',
              'but',
              'by',
              'can',
              "can't",
              'cannot',
              'com',
              'could',
              "couldn't",
              'did',
              "didn't",
              'do',
              'does',
              "doesn't",
              'doing',
              "don't",
              'down',
              'during',
              'each',
              'else',
              'ever',
              'few',
              'for',
              'from',
              'further',
              'get',
              'had',
              "hadn't",
              'has',
              "hasn't",
              'have',
              "haven't",
              'having',
              'he',
              "he'd",
              "he'll",
              "he's",
              'hence',
              'her',
              'here',
              "here's",
              'hers',
              'herself',
              'him',
              'himself',
              'his',
              'how',
              "how's",
              'however',
              'http',
              'i',
              "i'd",
              "i'll",
              "i'm",
              "i've",
              'if',
              'in',
              'into',
              'is',
              "isn't",
              'it',
              "it's",
              'its',
              'itself',
              'just',
              'k',
              "let's",
              'like',
              'me',
              'more',
              'most',
              "mustn't",
              'my',
              'myself',
              'no',
              'nor',
              'not',
              'of',
              'off',
              'on',
              'once',
              'only',
              'or',
              'other',
              'otherwise',
              'ought',
              'our',
              'ours',
              'ourselves',
              'out',
              'over',
              'own',
              'r',
              'same',
              'shall',
              "shan't",
              'she',
              "she'd",
              "she'll",
              "she's",
              'should',
              "shouldn't",
              'since',
              'so',
              'some',
              'such',
              'than',
              'that',
              "that's",
              'the',
              'their',
              'theirs',
              'them',
              'themselves',
              'then',
              'there',
              "there's",
              'therefore',
              'these',
              'they',
              "they'd",
              "they'll",
              "they're",
              "they've",
              'this',
              'those',
              'through',
              'to',
              'too',
              'under',
              'until',
              'up',
              'very',
              'was',
              "wasn't",
              'we',
              "we'd",
              "we'll",
              "we're",
              "we've",
              'were',
              "weren't",
              'what',
              "what's",
              'when',
              "when's",
              'where',
              "where's",
              'which',
              'while',
              'who',
              "who's",
              'whom',
              'why',
              "why's",
              'with',
              "won't",
              'would',
              "wouldn't",
              'www',
              'you',
              "you'd",
              "you'll",
              "you're",
              "you've",
              'your',
              'yours',
              'yourself',
              'yourselves'}
